name: marcustornell
favicon: null
layout_spectrum: 0.25739
typography_spectrum: 0.69786
title: Marcus Törnell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d81cc'
    - '#1d2937'
    - '#b6c6e0'
    - '#756653'
    - '#aa8c5d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
