name: marcustornell
favicon: null
layout_spectrum: 0.8365283068269491
typography_spectrum: 0.8028594844508916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.829065419267863
  lightness: 0.5602306465152651
  saturation: 0.24891451839357615
  rhythmicContrast: 0.3309006136842072
purpose: []
